// beste106-data.jsx — De Beste 106: jaarlijkse albumselectie (mock content; backend will replace)
//
// Concept: elk jaar selecteert Radio Scorpio 106 albums — de beste platen van het
// jaar (knipoog naar 106 FM). Eén editie per jaar, gerangschikt #001 → #106.
//
// Shape per edition (built below from compact tuples):
//   { id, year, editionNo, published, intro, albumCount,
//     featured: [{ rank, artist, title, url }]  // 6 highlights (top of the list)
//     albums:   [{ artist, title, url }]         // ranked order, #001 first }
// BESTE106.current points at the live (most recent) edition.

const B106_INTRO =
  "De Beste 106 is onze jaarlijkse balans: honderdzes platen die het jaar bepaalden, " +
  "gekozen door de Scorpio-vrijwilligers en uitgezonden in een volledige eindejaarsmarathon. " +
  "Van #106 tot de plaat van het jaaar op #001. Klik op een album voor audio / video / disco.";

// Compact tuples: [artist, title, url?]. url optional (backend vult artwork later in).
const B106_LISTS = {
  '2025': [
    ['Bill Orcutt & Mabe Fratti', 'Almost, Always', 'https://tinangelrecords.bandcamp.com'],
    ['Lankum', 'The Rushy Mountain'],
    ['Earl Sweatshirt', 'Live from the Garden'],
    ['The Smile', 'Cutouts II'],
    ['Slift', 'A Storm of Wings'],
    ['Nala Sinephro', 'Continuum'],
    ['Geese', 'Getting Killed'],
    ['Mabe Fratti', 'Sentir Que No Sabes'],
    ['FACS', 'Wish Defense'],
    ['Shinichi Atobe', 'Discipline of the Static'],
    ['Wendy Eisenberg', 'Viewfinder'],
    ['Bloodworm', 'Alone in Your Garden'],
    ['Yaya Bey', 'Do It Afraid'],
    ['Caroline', 'Caroline 2'],
    ['Saya Gray', 'Saya'],
    ['Underscores', 'Wallsocket II'],
    ['Sudan Archives', 'The BPM'],
    ['Oren Ambarchi', 'Hubris Reprise'],
    ['Pure Wrath', 'Hymn to the Woeful Hearts'],
    ['We Stood like Kings', 'Assassins'],
    ['Object Hours', 'Manhattan Marble'],
    ['Powerplant', 'Bridge of Sacrifice'],
    ['Mayssa Jallad', 'Marjaa: The Battle of the Hotels'],
    ['Rhododendron', 'Firmament'],
    ['Gelli Haha', 'Switcheroo'],
    ['Upupayama', 'Mystic Chords of Memory'],
    ['Diles Que No Me Maten', 'Hiriku'],
    ['Station Model Violence', 'Learn to Hate'],
    ['Deadtrees', 'Extinguished City'],
    ['Bassvictim', 'Going Home'],
    ['Lintworm', 'Cherries'],
    ['Irreversible Entanglements', 'Open the Gates'],
    ['Blood Orange', 'Essex Honey'],
    ['Home Front', 'Games of Power'],
    ['Danny Brown', 'Quaranta II'],
    ['Oneohtrix Point Never', 'Tremors'],
    ['Robyn', 'Dopamine'],
    ['KeiyaA', 'I H8 U'],
    ['Rosalía', 'Lux'],
    ['OKO DJ', 'Je suis la Terre'],
    ['Tomorrow Kings', 'Canned'],
    ['Carrier', 'Outer Shell'],
    ['Agriculture', 'The Spirit'],
    ['Armand Hammer', 'Crisis Phone'],
    ['Nusantara Beat', 'Bakar'],
    ['Maryam Saleh', 'Syrr'],
    ['Atol Atol Atol', 'Hytte'],
    ['DITZ', 'Don Enzo'],
    ['Clouds Indoor', 'Go Sleep'],
    ['Emily Wittbrodt', 'Wearing Words'],
    ['Assemblage 23', 'Mortal'],
    ['Butch Kassidy', 'Like Fire'],
    ['The Orchestra (For Now)', 'Impatient'],
    ['Been Stellar', 'Scream from New York, NY'],
    ['Ela Minus', 'DÍA'],
    ['Fievel Is Glauque', 'Rong Weicknes'],
    ['Helado Negro', 'Phasor'],
    ['Jaga Jazzist', 'Spiral Era'],
    ['Nourished by Time', 'Catching Chickens'],
    ['O.', 'WeirdOs'],
    ['Personal Trainer', 'Still Willing'],
    ['Tapir!', 'The Pilgrim, Their God and the King of My Decrepit Mountain'],
    ['Yard Act', 'Where\u2019s My Utopia?'],
    ['Cucina Povera', 'Tyhjyys'],
    ['DEADLETTER', 'Hysterical Strength'],
    ['Mount Eerie', 'Night Palace'],
    ['Horsegirl', 'Phonetics On and On'],
    ['Shabaka', 'Perceive Its Beauty, Acknowledge Its Grace'],
    ['Erika de Casier', 'Still'],
    ['Amaarae', 'Black Star'],
    ['Nilüfer Yanya', 'My Method Actor'],
    ['Loraine James', 'Gentle Confrontation'],
    ['Blawan', 'Woke Up Right Handed'],
    ['Carla dal Forno', 'Come Around'],
    ['Deeper', 'Careful!'],
    ['Dummy', 'Free Energy'],
    ['Floatie', 'Wholms'],
    ['Galya Bisengalieva', 'Polygon'],
    ['Jane Remover', 'Census Designated'],
    ['Quade', 'Invitation'],
    ['Rian Treanor', 'Hypnic Jerks'],
    ['Water From Your Eyes', 'Everyone\u2019s Crushed'],
    ['Sault', 'Acts of Faith'],
    ['Vegyn', 'The Road to Hell Is Paved with Good Intentions'],
    ['Maruja', 'Pain to Power'],
    ['Jockstrap', 'I<3UQTINVU'],
    ['Black Country, New Road', 'Forever Howlong'],
    ['Squid', 'Cowards'],
    ['Wu-Lu', 'Learning to Swim on Empty'],
    ['Kelela', 'In the Blue Light'],
    ['MIKE', 'Showbiz!'],
    ['billy woods', 'Golliwog'],
    ['Floating Points', 'Cascade'],
    ['Beth Gibbons', 'Lives Outgrown'],
    ['Chat Pile', 'Cool World'],
    ['Mannequin Pussy', 'I Got Heaven'],
    ['English Teacher', 'This Could Be Texas'],
    ['Crack Cloud', 'Red Mile'],
    ['The Hard Quartet', 'The Hard Quartet'],
    ['Cassandra Jenkins', 'My Light, My Destroyer'],
    ['Adrianne Lenker', 'Bright Future'],
    ['Cindy Lee', 'Diamond Jubilee'],
    ['Astrid Sonne', 'Great Doubt'],
    ['Vince Staples', 'Dark Times'],
    ['Tyler, the Creator', 'Chromakopia'],
    ['Sault', 'Together'],
  ],
  '2024': [
    ['Mabe Fratti', 'Sentir Que No Sabes'],
    ['Cindy Lee', 'Diamond Jubilee'],
    ['Adrianne Lenker', 'Bright Future'],
    ['The Smile', 'Wall of Eyes'],
    ['Nala Sinephro', 'Endlessness'],
    ['Beth Gibbons', 'Lives Outgrown'],
    ['MJ Lenderman', 'Manning Fireworks'],
    ['Jessica Pratt', 'Here in the Pitch'],
    ['Floating Points', 'Cascade'],
    ['Geordie Greep', 'The New Sound'],
    ['Tyler, the Creator', 'Chromakopia'],
    ['Charli xcx', 'Brat'],
    ['Father John Misty', 'Mahashmashana'],
    ['Kim Gordon', 'The Collective'],
    ['Vampire Weekend', 'Only God Was Above Us'],
    ['Waxahatchee', 'Tigers Blood'],
    ['English Teacher', 'This Could Be Texas'],
    ['Fontaines D.C.', 'Romance'],
    ['The Cure', 'Songs of a Lost World'],
    ['Mount Eerie', 'Night Palace'],
    ['Cassandra Jenkins', 'My Light, My Destroyer'],
    ['Astrid Sonne', 'Great Doubt'],
    ['Yaya Bey', 'Ten Fold'],
    ['Shabaka', 'Perceive Its Beauty, Acknowledge Its Grace'],
    ['Arooj Aftab', 'Night Reign'],
    ['Mdou Moctar', 'Funeral for Justice'],
    ['Kamasi Washington', 'Fearless Movement'],
    ['Helado Negro', 'Phasor'],
    ['Vince Staples', 'Dark Times'],
    ['ScHoolboy Q', 'Blue Lips'],
    ['JPEGMAFIA', 'I Lay Down My Life for You'],
    ['Clairo', 'Charm'],
    ['Nilüfer Yanya', 'My Method Actor'],
    ['Magdalena Bay', 'Imaginal Disk'],
    ['Jamie xx', 'In Waves'],
    ['Four Tet', 'Three'],
    ['Confidence Man', '3AM (La La La)'],
    ['Kelly Lee Owens', 'Dreamstate'],
    ['Bladee', 'Cold Visions'],
    ['Erika de Casier', 'Still'],
    ['Amaarae', 'Roses Are Red, Tears Are Blue'],
    ['Sega Bodega', 'Dennis'],
    ['Tirzah', 'Trip9love...???'],
    ['Crumb', 'AMAMA'],
    ['Chastity Belt', 'Live Laugh Love'],
    ['Friko', 'Where we\u2019ve been, Where we go from here'],
    ['Been Stellar', 'Scream from New York, NY'],
    ['Fat Dog', 'WOOF.'],
    ['Maruja', 'Connla\u2019s Well'],
    ['The Last Dinner Party', 'Prelude to Ecstasy'],
    ['Personal Trainer', 'Still Willing'],
    ['Crack Cloud', 'Red Mile'],
    ['Porridge Radio', 'Clouds in the Sky They Will Always Be There for Me'],
    ['Soccer Mommy', 'Evergreen'],
    ['Tycho', 'Infinite Health'],
    ['Caribou', 'Honey'],
    ['Bdrmm', 'Microtonic'],
    ['A Place to Bury Strangers', 'Synthesizer'],
    ['The Jesus and Mary Chain', 'Glasgow Eyes'],
    ['Pissed Jeans', 'Half Divorced'],
    ['Chat Pile', 'Cool World'],
    ['Knocked Loose', 'You Won\u2019t Go Before You\u2019re Supposed To'],
    ['Blood Incantation', 'Absolute Elsewhere'],
    ['Oranssi Pazuzu', 'Muuntautuja'],
    ['Ulcerate', 'Cutting the Throat of God'],
    ['Julia Holter', 'Something in the Room She Moves'],
    ['Nilüfer Yanya', 'Like I Say (I runaway)'],
    ['Los Campesinos!', 'All Hell'],
    ['Hovvdy', 'Hovvdy'],
    ['Wishy', 'Triple Seven'],
    ['Been Stellar', 'Sweet'],
    ['This Is Lorelei', 'Box for Buddy, Box for Star'],
    ['Brittany Howard', 'What Now'],
    ['Norah Jones', 'Visions'],
    ['St. Vincent', 'All Born Screaming'],
    ['Khruangbin', 'A La Sala'],
    ['Allie X', 'Girl with No Face'],
    ['Empress Of', 'For Your Consideration'],
    ['Rosie Tucker', 'Utopia Now!'],
    ['Hannah Frances', 'Keeper of the Shepherd'],
    ['Mannequin Pussy', 'I Got Heaven'],
    ['Glass Beach', 'Plastic Death'],
    ['Godspeed You! Black Emperor', '\u201cNo Title as of 13 February 2024\u201d'],
    ['Jlin', 'Akoma'],
    ['Loraine James', 'Gentle Confrontation'],
    ['Kassel Jaeger', 'Shifted in Dreams'],
    ['Rafael Toral', 'Spectral Evolution'],
    ['claire rousay', 'Sentiment'],
    ['Ekko Astral', 'Pink Balloons'],
    ['Ganser', 'Nothing You Do Matters'],
    ['Sprain', 'The Lamb as Effigy'],
    ['Couch Slut', 'You Could Do It Tonight'],
    ['Gouge Away', 'Deep Sage'],
    ['High Vis', 'Guided Tour'],
    ['Wand', 'Vertigo'],
    ['Cloud Nothings', 'Final Summer'],
    ['Hurray for the Riff Raff', 'The Past Is Still Alive'],
    ['Tomberlin', 'Radio Sweetheart'],
    ['Katie Gavin', 'What a Relief'],
    ['Aoife Nessa Frances', 'Protector'],
    ['Marie Davidson', 'City of Clowns'],
    ['Bnny', 'One Million Love Songs'],
    ['Been Stellar', 'Pumpkin'],
    ['Tapir!', 'The Pilgrim, Their God and the King of My Decrepit Mountain'],
    ['Bnny', 'Furious Bliss'],
    ['Wand', 'Hard Knox'],
  ],
  '2023': [
    ['Lankum', 'False Lankum'],
    ['Wednesday', 'Rat Saw God'],
    ['boygenius', 'the record'],
    ['Sufjan Stevens', 'Javelin'],
    ['Yo La Tengo', 'This Stupid World'],
    ['Mitski', 'The Land Is Inhospitable and So Are We'],
    ['ANOHNI and the Johnsons', 'My Back Was a Bridge for You to Cross'],
    ['Slowdive', 'everything is alive'],
    ['Black Country, New Road', 'Live at Bush Hall'],
    ['Yves Tumor', 'Praise a Lord Who Chews but Which Does Not Consume'],
    ['Caroline Polachek', 'Desire, I Want to Turn Into You'],
    ['Sampha', 'Lahai'],
    ['Jessie Ware', 'That! Feels Good!'],
    ['Romy', 'Mid Air'],
    ['Blur', 'The Ballad of Darren'],
    ['PJ Harvey', 'I Inside the Old Year Dying'],
    ['Lana Del Rey', 'Did You Know That There\u2019s a Tunnel...'],
    ['Olivia Rodrigo', 'GUTS'],
    ['Andre 3000', 'New Blue Sun'],
    ['Killer Mike', 'Michael'],
    ['JPEGMAFIA & Danny Brown', 'Scaring the Hoes'],
    ['billy woods & Kenny Segal', 'Maps'],
    ['Armand Hammer', 'We Buy Diabetic Test Strips'],
    ['Earl Sweatshirt & The Alchemist', 'Voir Dire'],
    ['Mavi', 'Shadowbox'],
    ['Wedidit', 'Lil Yachty'],
    ['Lil Yachty', 'Let\u2019s Start Here.'],
    ['Genesis Owusu', 'STRUGGLER'],
    ['Little Simz', 'No Thank You'],
    ['Noname', 'Sundial'],
    ['McKinley Dixon', 'Beloved! Paradise! Jazz!?'],
    ['Kelela', 'Raven'],
    ['Jorja Smith', 'falling or flying'],
    ['Tinashe', 'BB/ANG3L'],
    ['Cleo Sol', 'Heaven'],
    ['SZA', 'SOS'],
    ['Janelle Monáe', 'The Age of Pleasure'],
    ['Christine and the Queens', 'Paranoïa, Angels, True Love'],
    ['Sufjan Stevens', 'Reflections'],
    ['Laurel Halo', 'Atlas'],
    ['Nala Sinephro', 'Space 1.8'],
    ['Tim Hecker', 'No Highs'],
    ['Oneohtrix Point Never', 'Again'],
    ['Aphex Twin', 'Blackbox Life Recorder 21f'],
    ['Overmono', 'Good Lies'],
    ['Skee Mask', 'Resort'],
    ['Sofia Kourtesis', 'Madres'],
    ['Jana Rush', 'Dark Humor'],
    ['DJ Sabrina the Teenage DJ', 'Destiny'],
    ['Jessy Lanza', 'Love Hallucination'],
    ['Kelly Lee Owens', 'LP.8'],
    ['Avalon Emerson', '& the Charm'],
    ['George Riley', 'Running in Waves'],
    ['Water From Your Eyes', 'Everyone\u2019s Crushed'],
    ['Wednesday', 'Bull Believer'],
    ['Squid', 'O Monolith'],
    ['Model/Actriz', 'Dogsbody'],
    ['Gel', 'Only Constant'],
    ['Scowl', 'Psychic Dance Routine'],
    ['Militarie Gun', 'Life Under the Gun'],
    ['Speedy Ortiz', 'Rabbit Rabbit'],
    ['Hotline TNT', 'Cartwheel'],
    ['Feeble Little Horse', 'Girl with Fish'],
    ['Truth Cult', 'Walk the Wheel'],
    ['Militarie Gun', 'All Roads Lead to the Gun'],
    ['Foo Fighters', 'But Here We Are'],
    ['The National', 'First Two Pages of Frankenstein'],
    ['The National', 'Laugh Track'],
    ['Hannah Diamond', 'Perfect Picture'],
    ['100 gecs', '10,000 gecs'],
    ['Underscores', 'Wallsocket'],
    ['Jane Remover', 'Census Designated'],
    ['Quadeca', 'Scrapyard'],
    ['Liturgy', '93696'],
    ['Wolves in the Throne Room', 'Crypt of Ancestral Knowledge'],
    ['Sumac', 'The Healer'],
    ['Full of Hell', 'Coagulated Bliss'],
    ['Cattle Decapitation', 'Terrasite'],
    ['Tomb Mold', 'The Enduring Spirit'],
    ['Knoll', 'Metempiric'],
    ['Sweeping Promises', 'Good Living Is Coming for You'],
    ['Palehound', 'Eye on the Bat'],
    ['Indigo De Souza', 'All of This Will End'],
    ['Bully', 'Lucky for You'],
    ['Margaret Glaspy', 'Echo the Diamond'],
    ['Hether', 'Stop Being Naive'],
    ['Blondshell', 'Blondshell'],
    ['ratboys', 'The Window'],
    ['Youth Lagoon', 'Heaven Is a Junkyard'],
    ['Slauson Malone 1', 'EXcelsior'],
    ['Lonnie Holley', 'Oh Me Oh My'],
    ['ASIWYFA', 'Megafauna'],
    ['Greg Mendez', 'Greg Mendez'],
    ['Carla dal Forno', 'Come Around'],
    ['Loraine James', 'Gentle Confrontation'],
    ['Yaeji', 'With a Hammer'],
    ['Liv.e', 'Girl in the Half Pearl'],
    ['L\u2019Rain', 'I Killed Your Dog'],
    ['Genevieve Artadi', 'Forever Forever'],
    ['Cécile McLorin Salvant', 'Mélusine'],
    ['Irreversible Entanglements', 'Protect Your Light'],
    ['Shabaka', 'Afrikan Culture'],
    ['Anenon', 'Moons Melt Milk Light'],
    ['Fever Ray', 'Radical Romantics'],
    ['Róisín Murphy', 'Hit Parade'],
    ['Fever Ray', 'Even It Out'],
  ],
};

// Per-edition metadata.
const B106_META = [
  { id: '2025', year: 2025, editionNo: 'JG. \u201925', published: '31.12.2025' },
  { id: '2024', year: 2024, editionNo: 'JG. \u201924', published: '31.12.2024' },
  { id: '2023', year: 2023, editionNo: 'JG. \u201923', published: '31.12.2023' },
];

// Build editions (newest-first). Featured = the top 6 of the list.
const BESTE106 = {
  current: '2025',
  editions: B106_META.map(m => {
    const raw = B106_LISTS[m.id] || [];
    const albums = raw.map(([artist, title, url]) => ({ artist, title, url: url || '' }));
    const featured = albums.slice(0, 6).map((a, i) => ({ rank: i + 1, ...a }));
    return {
      ...m, intro: B106_INTRO, albumCount: albums.length,
      featured, albums,
    };
  }),
};

Object.assign(window, { BESTE106 });
